print("hello quelle et ta datte de naissansse")
a = int(input())
print("et ta mere quelle et son animal preferer")
c = str(input())
print(c)
print("ah et ton pere")
print(pere = str(input()))
pere = str(input())
print("et ou tu abite")
d = str(input())
print(d)
print("aurvoir !")
print("fin")
